In [4]:
import pandas as pd
import tensorflow as tf
import numpy as np

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

labels = ["Lucky Star 1", "Lucky Star 2", "Ball 1", "Ball 2", "Ball 3", "Ball 4", "Ball 5"]
column_labels = ["Lucky Star 1", "Lucky Star 2", "Ball 1", "Ball 2", "Ball 3", "Ball 4", "Ball 5", "Ball Delta", "Ball Y Delta", "LS Delta",
    "Ball 1 Repeat Last 5", "Ball 2 Repeat Last 5", "Ball 3 Repeat Last 5", "Ball 4 Repeat Last 5", "Ball 5 Repeat Last 5", "Lucky Star 1 Repeat Last 5", "Lucky Star 2 Repeat Last 5",
    "Ball 1 Repeat Last 10", "Ball 2 Repeat Last 10", "Ball 3 Repeat Last 10", "Ball 4 Repeat Last 10", "Ball 5 Repeat Last 10", "Lucky Star 1 Repeat Last 10", "Lucky Star 2 Repeat Last 10",
    "Ball 1 Repeat Last 20", "Ball 2 Repeat Last 20", "Ball 3 Repeat Last 20", "Ball 4 Repeat Last 20", "Ball 5 Repeat Last 20", "Lucky Star 1 Repeat Last 20", "Lucky Star 2 Repeat Last 20"
]
column_indices = {name: i for i, name in enumerate(column_labels)}


df = pd.read_excel("lottery-numbers-tracker.xlsx", sheet_name="EuroMillions", header=0)

df[column_labels].to_csv("euromillions-dataset.csv", index=None)

Num GPUs Available:  0


In [5]:
df = pd.read_csv('euromillions-dataset.csv')
df["Ball Y Delta 2"] = df["Ball Y Delta"]
df

Lucky Star 1  Lucky Star 2  Ball 1  Ball 2  Ball 3  Ball 4  Ball 5  \
0               6             7      12      27      36      37      42   
1               4            12      20      33      35      41      47   
2               1             9       3      19      29      35      37   
3               8            12      19      24      26      28      33   
4               4             8      12      22      27      33      45   
..            ...           ...     ...     ...     ...     ...     ...   
299             6             9       1      19      36      38      49   
300             9            10      10      25      29      34      45   
301             2             4       6      16      18      39      47   
302             7            12       5      14      35      36      39   
303             2             5       3      12      19      24      30   

     Ball Delta  Ball Y Delta  LS Delta  ...  Lucky Star 1 Repeat Last 10  \
0      4.555217      2.383275       1.0  ...                          2.0   
1      3.913119      5.126402       8.0  ...                          2.0   
2      4.974937      3.768289       8.0  ...                          0.0   
3      1.903943      2.986637       4.0  ...                          2.0   
4      4.366062      5.803447       4.0  ...                          1.0   
..          ...           ...       ...  ...                          ...   
299    6.791539      2.814249       3.0  ...                          0.0   
300    4.918079      3.143247       1.0  ...                          0.0   
301    6.169481      3.831449       2.0  ...                          1.0   
302         NaN           NaN       NaN  ...                          NaN   
303         NaN           NaN       NaN  ...                          NaN   

     Lucky Star 2 Repeat Last 10  Ball 1 Repeat Last 20  \
0                            1.0                    3.0   
1                            2.0                    1.0   
2                            3.0                    1.0   
3                            2.0                    2.0   
4                            2.0                    2.0   
..                           ...                    ...   
299                          1.0                    0.0   
300                          0.0                    0.0   
301                          0.0                    0.0   
302                          NaN                    NaN   
303                          NaN                    NaN   

     Ball 2 Repeat Last 20  Ball 3 Repeat Last 20  Ball 4 Repeat Last 20  \
0                      1.0                    0.0                    2.0   
1                      5.0                    2.0                    0.0   
2                      3.0                    4.0                    1.0   
3                      2.0                    0.0                    1.0   
4                      1.0                    1.0                    3.0   
..                     ...                    ...                    ...   
299                    1.0                    1.0                    0.0   
300                    0.0                    0.0                    0.0   
301                    0.0                    0.0                    1.0   
302                    NaN                    NaN                    NaN   
303                    NaN                    NaN                    NaN   

     Ball 5 Repeat Last 20  Lucky Star 1 Repeat Last 20  \
0                      2.0                          5.0   
1                      3.0                          2.0   
2                      1.0                          2.0   
3                      4.0                          4.0   
4                      2.0                          1.0   
..                     ...                          ...   
299                    0.0                          0.0   
300                    0.0                          0.0   
301                    0.0

In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# --- 1. Data Preparation ---

def create_sequences(data, seq_length, pred_cols):
    xs = []
    ys = []
    for i in range(len(data) - seq_length):
        x = data[i:(i + seq_length)].values
        y = data.iloc[i + seq_length, :pred_cols].values
        xs.append(x)
        ys.append(y)
    return np.array(xs), np.array(ys)

# --- 2. Load and Preprocess Data ---

# Example DataFrame creation
num_rows = 2000
num_cols = 32
random_seed = np.random.rand(num_rows, num_cols)

# Parameters
seq_length = 7  # Number of past rows to look at
pred_cols = 7  # Number of columns to predict
all_cols = 32
random_seed_length = 7 # Length of random seed

# Scale the data
scaler = StandardScaler()
df = pd.DataFrame(scaler.fit_transform(df[::-1]), columns=df.columns)

# Create sequences
X, y = create_sequences(df, seq_length, pred_cols)

# Split into training, validation, and test sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1)

# Input for the sequence
sequence_input = tf.keras.layers.Input(shape=(seq_length, all_cols))



In [7]:
scaler.inverse_transform(X[-1])

array([[ 2.00000000e+00,  7.00000000e+00,  1.00000000e+00,
         3.00000000e+00,  4.00000000e+00,  2.10000000e+01,
         2.90000000e+01,  4.73022198e+00,  7.66028720e+00,
         5.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         3.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         3.00000000e+00,  1.00000000e+00,  3.00000000e+00,
        -2.22044605e-16,  3.00000000e+00,  3.00000000e+00,
         2.00000000e+00,  7.66028720e+00],
       [ 6.00000000e+00,  9.00000000e+00,  1.00000000e+01,
         1.40000000e+01,  2.10000000e+01,  3.30000000e+01,
         5.00000000e+01,  5.57897840e+00,  6.56048779e+00,
         3.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00

In [63]:
# for testing sequences
# df = df[::-1]
# print(y[-1])
# print(df.iloc[-1].values[:7])

[ 6.  7. 12. 27. 36. 37. 42.]
[ 6.  7. 12. 27. 36. 37. 42.]


In [8]:
# --- 3. Model Definition ---

lstm_model = tf.keras.models.Sequential([
    # First 1D Convolutional layer
    tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(seq_length, all_cols)),
    tf.keras.layers.MaxPooling1D(pool_size=2),

    # LSTM layer
    tf.keras.layers.LSTM(64, return_sequences=True),
    tf.keras.layers.Dropout(0.2),

    # Reshape for Dense output
    tf.keras.layers.Reshape((64, 2)),  # Reshape to add a time dimension

    # Second 1D Convolutional layer
    tf.keras.layers.Conv1D(filters=32, kernel_size=3, activation='relu'),
    tf.keras.layers.MaxPooling1D(pool_size=2),

    # Flatten for Dense output
    tf.keras.layers.Flatten(),

    # Output layer
    tf.keras.layers.Dense(pred_cols),
])



In [9]:

# --- 4. Loss Function with Emphasis ---

def custom_loss(y_true, y_pred, random_target):
    # Calculate loss
    squared_error = tf.square(y_true - y_pred)
    weighted_mse_loss = tf.reduce_mean(squared_error)

    # MSE between prediction and random target
    mse_loss_random = tf.reduce_mean(tf.square(y_pred - random_target))

    # Combine the two losses (you can adjust the weights)
    return 0.75 * weighted_mse_loss + 0.25 * mse_loss_random

def generate_random_target(batch_size):
    targets = []
    for _ in range(batch_size):
        first_two = np.random.randint(1, 13, size=2)
        last_five = np.random.randint(1, 51, size=5)
        target = np.concatenate([first_two, last_five])
        targets.append(target)
    return np.array(targets)

# --- 5. Compile the Model ---

lstm_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                   loss=custom_loss)  # Use the custom weighted loss




In [10]:
X_train.shape

(267, 7, 32)

In [14]:
# --- 6. Train the Model ---

# Generate random seeds for training and validation data
train_random_seeds = np.random.randint(1, 51, size=(X_train.shape[0], random_seed_length))
val_random_seeds = np.random.randint(1, 51, size=(X_val.shape[0], random_seed_length))

# Custom training loop
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

epochs = 200
batch_size = 16

for epoch in range(epochs):
    epoch_loss = 0
    for i in range(0, X_train.shape[0], batch_size):
        # Get batch data

        X_batch = X_train[i:(i + batch_size)]
        y_batch = y_train[i:(i + batch_size)]
        random_seeds_batch = generate_random_target(X_batch.shape[0])

        with tf.GradientTape() as tape:
            # Get predictions
            predictions = lstm_model([X_batch], training=True)

            # Combine the two losses (you can adjust the weights)
            loss = custom_loss(y_batch, predictions, random_seeds_batch)

        # Compute and apply gradients
        gradients = tape.gradient(loss, lstm_model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, lstm_model.trainable_variables))

        epoch_loss += loss

    # Print epoch loss
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {epoch_loss / (X_train.shape[0] // batch_size)}")



Epoch 1/200, Loss: 131.0767364501953
Epoch 2/200, Loss: 134.37245178222656
Epoch 3/200, Loss: 134.67352294921875
Epoch 4/200, Loss: 139.9173583984375
Epoch 5/200, Loss: 138.18878173828125
Epoch 6/200, Loss: 136.75778198242188
Epoch 7/200, Loss: 132.17257690429688
Epoch 8/200, Loss: 133.7996826171875
Epoch 9/200, Loss: 135.7817840576172
Epoch 10/200, Loss: 130.0947723388672
Epoch 11/200, Loss: 134.62461853027344
Epoch 12/200, Loss: 140.5101318359375
Epoch 13/200, Loss: 138.22377014160156
Epoch 14/200, Loss: 133.22413635253906
Epoch 15/200, Loss: 136.03724670410156
Epoch 16/200, Loss: 133.9053192138672
Epoch 17/200, Loss: 133.4536895751953
Epoch 18/200, Loss: 135.4148406982422
Epoch 19/200, Loss: 135.10267639160156
Epoch 20/200, Loss: 133.21820068359375
Epoch 21/200, Loss: 130.6661376953125
Epoch 22/200, Loss: 138.61148071289062
Epoch 23/200, Loss: 139.01995849609375
Epoch 24/200, Loss: 143.16989135742188
Epoch 25/200, Loss: 135.34939575195312
Epoch 26/200, Loss: 141.93634033203125
Epoch

KeyboardInterrupt: 

In [15]:
# --- 8. Evaluate the Model ---

val_loss = 0
for i in range(0, X_val.shape[0], batch_size):
    X_batch = X_val[i:i + batch_size]
    y_batch = y_val[i:i + batch_size]
    random_target_batch = generate_random_target(X_batch.shape[0])

    predictions = lstm_model([X_batch], training=False)
    loss = custom_loss(y_batch, predictions, random_target_batch)
    val_loss += loss

print(f"Validation Loss: {val_loss / (X_val.shape[0] / batch_size)}")

Validation Loss: 135.19044494628906


In [16]:
# --- 9. Make Predictions ---

# Generate a random seed for prediction
prediction_random_seed = np.random.randint(1, 51, size=(1, random_seed_length))

# Get the last sequence from X_val and reshape it for prediction
last_sequence = X[0].reshape(1, seq_length, all_cols)

# Make a prediction using the last sequence and the random seed
prediction = lstm_model.predict([last_sequence])

# Inverse transform to get predictions in the original scale
prediction = scaler.inverse_transform(np.concatenate((prediction, np.zeros((prediction.shape[0], all_cols - pred_cols))), axis=1))[:, :pred_cols]

prediction

1/1 [==============================] - 0s 14ms/step


array([[ 8.55346816, 12.34280668, 49.89598399, 63.60310763, 77.788169  ,
        82.04879179, 83.22747375]])